### ISSUE TITLE
[Compat] Registry config file.

### ISSUE THREAD

**Issue by Moomallowz** [jsburger/Architects-Palette#12]
Several blocks in this mod conflict with other mods.
Would it be too much to ask to include a config.toml that allows us to disable crafting/villager trades for all blocks in this mod?

(Should probably clarify- not one config option that disables everything, but multiple config options for each block.)
(Another clarification- when I say "each block", I mean "each category of blocks": for example, the Osseous Brick Stairs wouldn't get their own config option, instead it'd be toggled by the Osseous Blocks config option.)

**Comment by jsburger** [comment]
I would be willing to add config options for villager trades some time. Anything else is already able to be changed with datapacks, so I will not be adding configs for those.

**Comment by Moomallowz** [comment]
Oh, true. Thanks for the response!
