### ISSUE TITLE
Can not launch MC using Hydrogen and AP

### ISSUE THREAD

**Issue by HyperlyBola** [jsburger/Architects-Palette#13]
[crash-2021-06-03_19.12.36-client.txt](https://github.com/jsburger/Architects-Palette/files/6594984/crash-2021-06-03_19.12.36-client.txt)

When I remove Architects Palette from my mods list I can launch MC just fine with Hydrogen, but with it I cant launch the game.

**Comment by jsburger** [comment]
I've been informed that this is an issue for the fabric version, and that Slomax is fixing it next release. If you want, you can reopen this on the fabric repo.
