### ISSUE TITLE
Twisted Leaves does not drop saplings

### ISSUE THREAD

**Issue by WenXin20** [jsburger/Architects-Palette#21]
`Minecraft v1.18.1`
`Forge v39.0.59`
`Architect's Palette v1.1.0`

Twisted Leaves drop itself when it decays instead of a sapling.

**Comment by jsburger** [comment]
Fixed [in this commit](https://github.com/jsburger/ap-assets/commit/45e5f667f9466bac58e264e052fea97d16ac66bf)
Thank you for reporting, will be released in 1.1.1
