### ISSUE TITLE
Missing Limestone....

### ISSUE THREAD

**Issue by johalun** [jsburger/Architects-Palette#23]
Hey!

I just updated my Valhelsia Enhanced Vanilla from 1.0.7 to 1.1.0 which updates this mod from 1.3-1.18-rc3 to 1.6. When I logged in to my world I noticed all the Limestone and Limestone bricks where missing from my builds. Also, my villagers who trade emeralds for Limestone now trade Air instead...

Any ideas?

**Comment by Slomaxonical-907** [comment]
Yep, limestone was renamed to myonite in 1.5,(read changelog on cf for more info)... The pack devs shoudve warned you ig. I hope you made some backups XD

**Comment by johalun** [comment]
Ah I see. Yep, got backups. Hmm, you know any good tool to do a block replacement in a big area?

**Comment by johalun** [comment]
I'm surprised though that renaming a block would cause it to vanish.. I'd assume block are references by an ID and not their name..

**Comment by Slomaxonical-907** [comment]
I guess worldedit is what u need. And you are right, I changed their id to myonite too (that's why limestone is not recognized anymore)... I shoud use DataFixers for cases like this but they seemed too complex I aint ready for them ;)
