### ISSUE TITLE
[Loading Failure]

### ISSUE THREAD

**Issue by subatomicsquid** [jsburger/Architects-Palette#26]
I've been trying to use Architect's Palette in a Create Above & Beyond playthrough, but I continue getting the same "java.lang.reflect.InvocationTargetException: null" response upon loading up the game. I'm running my mods on 1.18.2-forge-40.1.0, and the mods I'm using are as follows:

- Architects-Palette-1.18.1-1.1.3
- Chisel-MC1.12.2-1.0.2.45
- create-mc1.18.2_v0.4.1
- CTM-MC1.12.2-1.0.2.31
- flywheel-forge-1.18-0.6.2
- jei-1.18.2-9.5.5.17

The full crash report can be found here:
[crash-2022-05-24_21.49.20-fml.txt](https://github.com/jsburger/Architects-Palette/files/8767559/crash-2022-05-24_21.49.20-fml.txt)

(I am a little new to this, so please do let me know if you need more information than I've given)

**Comment by jsburger** [comment]
Architect's Palette doesn't run on 1.18.2 yet. The update should be relatively soon, and I'll close this issue when it's out.

**Comment by subatomicsquid** [comment]
Holy crap, thank you for replying so quickly! I appreciate the response.

**Comment by jsburger** [comment]
I remembered I needed to close this yesterday, but was too lazy to do so. The update is out now.
