### ISSUE TITLE
[1.19] Unobtanium dupe

### ISSUE THREAD

**Issue by Geartwo** [jsburger/Architects-Palette#27]
![image](https://user-images.githubusercontent.com/4224642/181360957-05684fed-f179-4489-b83c-c6184a3c8ec9.png)
![image](https://user-images.githubusercontent.com/4224642/181361010-207c00b3-8a90-4645-b429-d0701977a9c1.png)

I think the pictures are enough

**Comment by MrJorman** [comment]
ahhahgah you retard.

**Comment by jsburger** [comment]
@MrJorman 
Hey, shit for brains, do me a favor and don't go around calling people retards on my issue board.

Closing this issue; unobtanium is intentionally crafted like this. It's meant to be a funny material.
