### ISSUE TITLE
Charged abyssaline is super laggy / cpu intensive

### ISSUE THREAD

**Issue by erisdev** [jsburger/Architects-Palette#3]
The pulsing light level causes constant light updates, which, it's a cool effect, but it makes my cpu fans kick into high gear and i suspect on a less powerful machine it would make the frame rate chug.

I'd say just give it a fixed light level and use a normal animated texture, and let the texture do the work of conveying "pulsing glow" for you.

**Comment by jsburger** [comment]
Yeah, sorry about that. I recently became aware of the issue myself after playing on another PC. There are already plans to remove or mitigate the effect for now in the next update.

**Comment by jsburger** [comment]
This should be resolved now, but I would like to keep tabs on Abyssaline's performance. The pulsing is gone, but the individual blocks still change their light level to 1 after being charged. Reopen if this becomes an issue.

**Comment by erisdev** [comment]
thanks for the quick response, love the mod btw :+1:
