### ISSUE TITLE
[Suggestion] Let the direction of flint pillar arrows/chevrons be flipped

### ISSUE THREAD

**Issue by saltyseadoggo** [jsburger/Architects-Palette#35]
I would love to be able to flip the direction in which the flint pillar block's arrow/chevron pattern points, but this is not possible with their current implementation- they always point down when vertical, and south/west when horizontal. This way, they could point in the direction an adjacent conveyor belt or item pipe is moving, for example, for added aesthetics.
I thought of two possible implementations for this idea:
1) Change the flint pillar's block class to one that can face any of the six directions, instead of using an `axis` blockstate. This would be the 'cleanest' solution, and the pillars' placement would be intuitive, but, iirc, adding more blockstates to an existing block can cause issues with compat with worlds loaded with old versions of the mod.
2) Add a "Reversed Flint Pillar" block obtainable by crafting or stonecutting with the regular version that just has the chevrons facing the opposite way. This would allow one to point the arrows whichever way they want, but horizontal placement could be a bit annoying due to not knowing which way each kind faces without placing them.

**Comment by jsburger** [comment]
Flint Pillars can already be placed in 6 directions, at least on the latest version. Unfortunately, I don't backport feature updates if you happen to be on 1.16 or something.

**Comment by saltyseadoggo** [comment]
Oop, yep, I'm on 1.16. My apologies.~
