### ISSUE TITLE
Dedicated server crash: "Attempted to load class net/minecraft/client/resources/model/BakedModel for invalid dist DEDICATED_SERVER"

### ISSUE THREAD

**Issue by unilock** [jsburger/Architects-Palette#36]
Starting a dedicated server with the mod installed causes it to crash during startup.

To reproduce:
1. Create a Forge 1.18.2 server.
2. Install Architect's Palette.
3. Start server.
4. Server crashes.

Versions:
- Minecraft `1.18.2`
- Forge `40.2.0`
- Architect's Palette `1.3.0`

Crash log: https://gist.github.com/unilock/d57b4610447e77675e5fd715f346bbc9

**Comment by jsburger** [comment]
Ty for the speedy report. I neglected to check if the server still ran because this mod just adds blocks. New build will go out relatively soon.

**Comment by jsburger** [comment]
The update is now released
