### ISSUE TITLE
[1.19.2 - Bug] All Myonite vertical slab recipes broken

### ISSUE THREAD

**Issue by DelviousCrafts** [jsburger/Architects-Palette#39]
Appears that the name myonite got changed in the registry but not in the recipes jsons for vertical slabs only. All other recipes seem to be working just fine. 

Versions:
- Minecraft: 1.19.2
- Forge: 43.2.8
- Architect's palette: 1.3.2

**Comment by KodYazanDruid** [comment]
Same for 1.18.2

**Comment by jsburger** [comment]
Fixed on both versions
