### ISSUE TITLE
Unobtainium Replication

### ISSUE THREAD

**Issue by CraftyZombie** [jsburger/Architects-Palette#48]
Forgive me if this is an intentional quirk of unobtainium, but unobtainium blocks require 4 ingots to craft, but can be crafted back into 5, leading to an infinite supply of the material.

**Comment by CraftyZombie** [comment]
https://github.com/jsburger/Architects-Palette/blob/1.20.1/src/main/resources/data/architects_palette/recipes/unobtanium.json

**Comment by jsburger** [comment]
This is in fact intentional behavior, no trouble.
