### ISSUE TITLE
[loading failed/crash] "Mod Loading Failed" screen, citing that the mod ran into issues in both the load_registries and error event phases

### ISSUE THREAD

**Issue by Corvus20** [jsburger/Architects-Palette#5]
Using the latest builds of forge and Architect's Palette available on GDLauncher. Unearthed has an error too but thats not an issue for here. 

![image](https://user-images.githubusercontent.com/75586106/109026011-45e47b00-768d-11eb-905f-63e17fc1c967.png)

[crash-2021-02-24_10.31.23-fml.txt](https://github.com/jsburger/Architects-Palette/files/6037094/crash-2021-02-24_10.31.23-fml.txt)

**Comment by jsburger** [comment]
Based on the crash log and some snooping around I did. It looks like this is an issue with FerriteCore, which may have been fixed just today.
https://www.curseforge.com/minecraft/mc-mods/ferritecore/files/3215757

**Comment by jsburger** [comment]
Gonna close this, as I'm fairly confident that this was the issue. Reopen if need be.
