### ISSUE TITLE
[Feature Request] Immersive Portals compat

### ISSUE THREAD

**Issue by erisdev** [jsburger/Architects-Palette#6]
Don't know if this is even reasonable to ask for, but right now the warping crafting type (which is a really cool concept!) doesn't work with immersive portals, since it replaces the portal mechanics entirely. I'd love to be able to use both mods together without losing access to warped materials. Maybe there could be a cute visual effect too?

**Comment by jsburger** [comment]
As of this commit, warping works with immersive portals, and should work with similar mods. Only issue is that warping is one sided now. Which is fixable, but I don't want to figure out all the systems required to do so.

**Comment by erisdev** [comment]
Thank you! I think, at least, the warping recipes being one-sided is easily rationalized. I appreciate the work you've done.
